language: c
os:
- linux
- osx
script:
- make p.so
- echo "Preparing version $TRAVIS_BRANCH-$TRAVIS_COMMIT"
- zip -r embedPy_$TRAVIS_OS_NAME-$TRAVIS_BRANCH.zip p.q p.k test.q tests m64/p.so
  l64/p.so LICENSE README.md || true
- echo "Packaged as embedPy_$TRAVIS_OS_NAME-$TRAVIS_BRANCH.zip"
compiler:
- clang
- gcc
deploy:
  provider: releases
  api_key: $GITHUB_APIKEY
  file_glob: true
  file: embedPy_*.zip
  skip_cleanup: true
  on:
    tags: true
notifications:
  slack: $KXSLACK
