language: c
os:
- linux
- osx
script:
- make p.so
- echo "Preparing version $TRAVIS_BRANCH-$TRAVIS_COMMIT"
- zip -r embedPy_$TRAVIS_OS_NAME-$TRAVIS_BRANCH.zip p.q p.k test.q tests m64/p.so
  l64/p.so LICENSE README.md || true
- echo "Packaged as embedPy_$TRAVIS_OS_NAME-$TRAVIS_BRANCH.zip"
compiler:
- clang
- gcc
deploy:
  provider: releases
  api_key:
    secure: NFeVGp67Z7cd7W2frAifWgKB9ugz7OH9mvPd2XM7tKH5errifQ5JCQZjeppkhq9AKu/aQywo93+2s8IBSxoH/WqWtRUJ2s8+/GzDr+OVQh+0eKs2hEb2G5ktP7TFfhooywxD9NVjhhK8mEqJCSkjw3bapyWS8SQw9lf0e35zl/+LylWpREheCI7hDO+AcESxy/hKIzo6E8g8w9a92juGZM7iB0YkH9n7B1RHbnimo0YHsvAHL4kivhAWE6CxvfOlfRP/5vDkIgsHPLzg/kVeuR1K5ayXTFMSspbaqE6q/Fpm/e1OVqYEmaE0tz2Oasg+O955mZC0WT6kteObCWnyScaXUm4ge0DEdYSKSCeXeXkupYI/NzKr972slmrq0GIzjq7lAnFhCTxKh2iXlFDF1NhepqRX7PgTA6zjC3PXMi0ZjZ27oQ4LVVNXKZWq1xPsuP5+qIhumG9VbnpnPGs9eo0qYQv87K6FrqeIijntjBKuir2HgWHNP4Enfdq8hwUx9biLyAlEI7YJ0PIsTejtwkSf4PuRx3/kSp5G9lKLnXP2bn4a9uu7ycSFtXadrN0AXXVXI6s7v5ntuVvnfyJXsaLHOzS5bqnb2TyrIzuQ2dgBgbszhP8BaTFkXDPL9UILclIfBTBhfieVSGcP6eCp7CiSSoQBxmAkFrvJxTP137o=
  file_glob: true
  file: embedPy_*.zip
  skip_cleanup: true
  on:
    tags: true
notifications:
  slack:
    secure: xKR2fdn+FPc0lmERQAEOBV1G8mZTy81+RSrKARjT7Z+/+TYixfEgRi7k4IZm4BNlu0Vl++zTmsml1Z8Yy71fNj4OfP+MqILRGyC2JbmWaUjoXyJOqyj3yu8pVRSDoHXkzVGuMHzvnjCvus1Q8iawOid9ekfbcRbatyi29VAQyt9BGYpl5AhPMM8FgWtplgnB71ZO3ptxy6Frj/5cdMilaIO65CRz+APoofFOlTwJLG8+EmIagKUqZYS6ZSNNtRpMqPW6UgeesX40hSQTLTV7DLnKgWBGMTnYvOWIwnD3lvWJ7A5NOxrDlliiaFm1GaNZ5OJ6XdFMsUqrm39GyLP5zJa/WKdpUaCMQshawVoZCI3kIPHVFMKIDH0zEY48zhlzeyScUVImXdYxvjVGY3NsF0Pc+a1H5L06ikJPl2nqk6/c+IHSV2slTxAjeUF9ULEt0jaGS47gbi9Ykwhu0t4BYfefXr+7izLTxWU9mBoJDT98iVMLYGrPs5sSg+JYGzz1Fq/KjnFdq8sYK3HUTF8a9EIWs91cJR6pK5jIERy8TZQShC0An3pwm9p9hGv4a6cwTxa6vRujpomeExO9CCWP5Aek7SX5kem4R5nwJVz0wX6iHHA7/RS1Ckt4y5XkVJ9Dy1XvP+YMenKtkVONsV0ZVhxw14O89cuLWZS+qePUNy0=
