language: c
os:
- linux
- osx
script:
- make p.so
- echo "Preparing version $TRAVIS_BRANCH-$TRAVIS_COMMIT"
- zip -r embedPy_$TRAVIS_OS_NAME-$TRAVIS_BRANCH.zip p.q p.k test.q tests m64/p.so l64/p.so LICENSE README.md || true
- echo "Packaged as embedPy_$TRAVIS_OS_NAME-$TRAVIS_BRANCH.zip"
compiler:
- clang
- gcc
deploy:
 provider: releases
 api_key:
  secure: pgMeCCGx+KeIwUl2hVRcOl8hdgYtw0pMP9qeqI/m5X22jw+DHjcNcGMtFRxuNqRPPRknVS/QLD84i4dvZoEEagIwiO3/Ek+iu1qqqlPZfVzHbdRRyAfiMCQyZCyFz+I8wbLwWK18uc2wguC88hnpZ6UnuSUdNN6xdwG5zhpBLYeBTqwTqX3IlYj9Jwcwooy3HpBTrDSJ6Qog6FeMqZUx+dbCV534OoIFee5bxRslM83TegZgsw78NFPdrI65B6xz+LOtNaNdYaADalkL+9c1NOedlPq9mYTYn0rm2iqQAyAjFLAAUIcgdHUyHVdOMWalh3W5ORwVhryTOxS+chcHbJprRvInjdiD3atxcur9vDpGHRyxf92ZAzb33dNhe1Hrglqt2Gkcx0MJ+/UaIDuUY2SB4/xXvh5fc2Qvl07oxMSnTAlZa7EwFJmy6Hvft1hpWUidjD6BWN2QNJA38aW0twqU/dpfsoh8IKaCvb09DC6VQ7kOSd/5MefxaV/jrF7gTHpByT16jjvZ0Uzq6deYyXRz704mxJPEg5bUnvoyCeVNzyOh+1+6whBgb9wbUpNF0HNWOmSmjsmKbRdWRj3r7r1R5DO+7e/J1lPRDZS326YzpmFLa1sexI6a0g51e6ardR9G2F70SakV0Fhlh1d1KENfP7fChAKyDMfqwgxXZCU=
 file_glob: true
 file: embedPy_*.zip
 skip_cleanup: true
 on:
  branch: travis
