language: c
os:
- linux
- osx
script:
- make p.so
- echo "Preparing version $TRAVIS_BRANCH-$TRAVIS_COMMIT"
- zip -r embedPy_$TRAVIS_OS_NAME-$TRAVIS_BRANCH.zip p.q p.k test.q tests m64 l64 LICENSE README.md || true
- echo "Packaged as embedPy_$TRAVIS_OS_NAME-$TRAVIS_BRANCH.zip"
compiler:
- clang
- gcc
