language: c
os:
- linux
- osx
script:
- make p.so
- echo "Preparing version $TRAVIS_BRANCH-$TRAVIS_COMMIT"
- zip -r embedPy_$TRAVIS_OS_NAME-$TRAVIS_BRANCH.zip p.q p.k test.q tests m64/p.so
  l64/p.so LICENSE README.md || true
- echo "Packaged as embedPy_$TRAVIS_OS_NAME-$TRAVIS_BRANCH.zip"
compiler:
- clang
- gcc
deploy:
  provider: releases
  api_key: $GITHUB_APIKEY
  file_glob: true
  file: embedPy_*.zip
  skip_cleanup: true
  on:
    tags: true
notifications:
  slack:
    secure: xKR2fdn+FPc0lmERQAEOBV1G8mZTy81+RSrKARjT7Z+/+TYixfEgRi7k4IZm4BNlu0Vl++zTmsml1Z8Yy71fNj4OfP+MqILRGyC2JbmWaUjoXyJOqyj3yu8pVRSDoHXkzVGuMHzvnjCvus1Q8iawOid9ekfbcRbatyi29VAQyt9BGYpl5AhPMM8FgWtplgnB71ZO3ptxy6Frj/5cdMilaIO65CRz+APoofFOlTwJLG8+EmIagKUqZYS6ZSNNtRpMqPW6UgeesX40hSQTLTV7DLnKgWBGMTnYvOWIwnD3lvWJ7A5NOxrDlliiaFm1GaNZ5OJ6XdFMsUqrm39GyLP5zJa/WKdpUaCMQshawVoZCI3kIPHVFMKIDH0zEY48zhlzeyScUVImXdYxvjVGY3NsF0Pc+a1H5L06ikJPl2nqk6/c+IHSV2slTxAjeUF9ULEt0jaGS47gbi9Ykwhu0t4BYfefXr+7izLTxWU9mBoJDT98iVMLYGrPs5sSg+JYGzz1Fq/KjnFdq8sYK3HUTF8a9EIWs91cJR6pK5jIERy8TZQShC0An3pwm9p9hGv4a6cwTxa6vRujpomeExO9CCWP5Aek7SX5kem4R5nwJVz0wX6iHHA7/RS1Ckt4y5XkVJ9Dy1XvP+YMenKtkVONsV0ZVhxw14O89cuLWZS+qePUNy0=
