language: c
os:
- linux
- osx
git:
  depth: 1

before_install:
- if [ $TRAVIS_OS_NAME = osx ]; then brew outdated pyenv || brew upgrade pyenv ; export PYTHON_CONFIGURE_OPTS="--enable-framework" ; fi
- PY=$(pyenv install --list | grep -v - |grep -v [a-z]|grep -e  '^  3\.5\..*'|tail -1)
- pyenv install $PY && pyenv local $PY
script:
- if [ $TRAVIS_OS_NAME = osx ]; then pyenv init - > pyenv.init && source pyenv.init ; fi
- if [ $TRAVIS_OS_NAME = linux ]; then QLIBDIR=l64;OD=$L64; elif [ $TRAVIS_OS_NAME = osx ]; then QLIBDIR=m64;OD=$M64; else echo "unknown OS ('$TRAVIS_OS_NAME')" >&2; exit 1; fi; export QLIBDIR
- mkdir q && export QHOME=$(pwd)/q && export PATH=$QHOME/$QLIBDIR:$PATH
- curl -o q/q.zip -L $OD
- unzip -d q q/q.zip
- make p.so
- cp [ml]64/p.so q/$QLIBDIR;
- echo "Preparing version $TRAVIS_BRANCH-$TRAVIS_COMMIT"
- tar czf embedPy_$TRAVIS_OS_NAME-$TRAVIS_BRANCH.tgz p.q p.k test.q tests [ml]64/p.so LICENSE README.md
- echo "Packaged as embedPy_$TRAVIS_OS_NAME-$TRAVIS_BRANCH.zip"
- if [[ "x$QLIC_KC" != "x" ]]; then
    echo -n $QLIC_KC |base64 --decode > q/kc.lic;
    pip3 -q install -r tests/requirements.txt;
    q test.q -q;
  else
    echo no kdb+ not testing;
  fi
compiler:
- clang
deploy:
  provider: releases
  api_key: "$GITHUB_APIKEY"
  file_glob: true
  file: embedPy_$TRAVIS_OS_NAME-$TRAVIS_BRANCH.tgz
  skip_cleanup: true
  on:
    tags: true
jobs:
  include:
    - stage: docker
      sudo: required
      services:
        - docker
      before_install: skip
      script:
        - docker build -t kxsys/embedpy:latest -f docker/Dockerfile .
        - docker tag kxsys/embedpy:latest kxsys/embedpy:$TRAVIS_BRANCH
      deploy:
        provider: script
        script:
          - echo $DOCKER_PASSWORD|docker login --username $DOCKER_USERNAME --password-stdin && docker push kxsys/embedpy:latest && docker push kxsys/embedpy:$TRAVIS_BRANCH
        skip_cleanup: true
        on:
          tags: true
          condition: $TRAVIS_BRANCH =~ ^[0-9]+\.
notifications:
  slack:
    secure: "MR5icOywJJSFy7gnxeNXACN2nKiHniVgX1myiF+H9U4wsW6+2BHzPMcmy3FIUjL3Tb+PcAfq7+8RHerAx/XEB7nsVJsu9TyCjYWgaqx5Z9WNIDcjQh4wnFurhlzqrwF4gjelY+wxdffpsKUVaP+fermWbqHvv1aPPk4l3xEonXZ5J5uNkPTPufILzpx2cTxWg08o6PhvgjTrombs+9rGxahU8cfUSwTVuPCcPtOy70kcaowFfrU2kWzQk88NM5d/TVZdkOmGhLqVWSvRgaLXFkGYwRWatT7divlXX2evYwdYib++RUUhxDGZwJjdFCbGDNjrMyBbJOrCkndxLSATd6gN76dWuWsVV49K4YB0Mw5uFJFt6J0TnbkJC5Zsl9i6vik7m3anuIPOeAI54/wtlCvMeIpt2eQCPMy7xXu2hXNUR4ofM4yaVjKz69b5JIZ1o3vBxPQxAqIYggqPsTaLJM4vLpZlncnViBkfO/La5V9sJNQy3IyLSlEKry3giYfo8wbHT3PLn1xG7HW2DJ7hRn19yzTkCCNfaSzvq8YlSQvjNlPCO566ykYYG6SzG/NnbDqJAqydhpFuNC7ZB5dPuAOoDANCGs4gtfYKia+ZVxKYn25Y52vdi34L5TO83BUrsQWgytb0J6a4jDe3PWLVFSP7XLiy4h8Tyv76+Hm4lHk="
