package:
  name: embedpy
  version: {{ environ.get('EMBEDPY_VERSION', 'noversion') }}

source:
  path: ..

build:
  detect_binary_files_with_prefix: False
  script_env:
    QLIC_KC

requirements:
  build:
    - m2w64-make                     [win]
    - {{ compiler('c') }}
  host:
    - python >=3.5,<3.7
    - kdb
  run:
    - python >=3.5,<3.7
    - kdb
test:
  source_files:
    - test.q
    - tests/
  requires:
    - matplotlib
    - numpy
    - scipy
    - tensorflow
    - pandas
    - beautifulsoup4

about:
  home: https://github.com/KxSystems/embedPy
  summary: allows the kdb+ interpreter to manipulate Python objects
